"""add cart + cart_line tables

Revision ID: 119f036526e0
Revises: d458a3812d35
Create Date: 2026-04-25 22:11:16.066919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119f036526e0'
down_revision: Union[str, None] = 'd458a3812d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('session_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_customer_id'), 'cart', ['customer_id'], unique=True)
    op.create_index(op.f('ix_cart_session_token'), 'cart', ['session_token'], unique=True)
    op.create_table('cart_line',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'product_id', name='uq_cart_line_cart_product')
    )
    op.create_index(op.f('ix_cart_line_cart_id'), 'cart_line', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_line_product_id'), 'cart_line', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_line_product_id'), table_name='cart_line')
    op.drop_index(op.f('ix_cart_line_cart_id'), table_name='cart_line')
    op.drop_table('cart_line')
    op.drop_index(op.f('ix_cart_session_token'), table_name='cart')
    op.drop_index(op.f('ix_cart_customer_id'), table_name='cart')
    op.drop_table('cart')
    # ### end Alembic commands ###
