"""add prod_code to product

Revision ID: d458a3812d35
Revises: f5d215d1f6f6
Create Date: 2026-04-25 19:33:53.103425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd458a3812d35'
down_revision: Union[str, None] = 'f5d215d1f6f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('prod_code', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_product_prod_code'), 'product', ['prod_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_prod_code'), table_name='product')
    op.drop_column('product', 'prod_code')
    # ### end Alembic commands ###
