"""initial schema

Revision ID: f5d215d1f6f6
Revises: 
Create Date: 2026-04-25 17:48:08.771630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5d215d1f6f6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('legacy_wsm_prefix', sa.String(length=8), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_is_featured'), 'brand', ['is_featured'], unique=False)
    op.create_index(op.f('ix_brand_legacy_wsm_prefix'), 'brand', ['legacy_wsm_prefix'], unique=False)
    op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=True)
    op.create_index(op.f('ix_brand_slug'), 'brand', ['slug'], unique=True)
    op.create_table('category',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('full_path', sa.String(length=1000), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_path', name='uq_category_full_path')
    )
    op.create_index(op.f('ix_category_depth'), 'category', ['depth'], unique=False)
    op.create_index(op.f('ix_category_full_path'), 'category', ['full_path'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    op.create_index(op.f('ix_category_slug'), 'category', ['slug'], unique=False)
    op.create_table('customer',
    sa.Column('customer_number', sa.String(length=20), nullable=False),
    sa.Column('tier', sa.Enum('RETAIL', 'JOBBER', 'DEALER', 'MUNICIPALITY', name='customer_tier'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('fax', sa.String(length=32), nullable=True),
    sa.Column('sales_rep_code', sa.String(length=20), nullable=True),
    sa.Column('is_tax_exempt', sa.Boolean(), nullable=False),
    sa.Column('tax_exempt_cert_number', sa.String(length=100), nullable=True),
    sa.Column('tax_exempt_state', sa.String(length=2), nullable=True),
    sa.Column('payment_terms', sa.String(length=20), nullable=True),
    sa.Column('credit_limit_usd', sa.Integer(), nullable=True),
    sa.Column('retail_view_markup_percent', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_customer_number'), 'customer', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_index(op.f('ix_customer_tier'), 'customer', ['tier'], unique=False)
    op.create_table('warehouse',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('emits_own_facs_file', sa.Boolean(), nullable=False),
    sa.Column('facs_route_label', sa.String(length=20), nullable=False),
    sa.Column('ship_via_default', sa.String(length=64), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_code'), 'warehouse', ['code'], unique=True)
    op.create_table('contract',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('group_code', sa.String(length=100), nullable=True),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('pricing_formula', sa.String(length=500), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('partner_program', sa.String(length=100), nullable=True),
    sa.Column('partner_organization', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_brand'), 'contract', ['brand'], unique=False)
    op.create_index(op.f('ix_contract_customer_id'), 'contract', ['customer_id'], unique=False)
    op.create_index(op.f('ix_contract_expiration_date'), 'contract', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_contract_group_code'), 'contract', ['group_code'], unique=False)
    op.create_index(op.f('ix_contract_part_number'), 'contract', ['part_number'], unique=False)
    op.create_index(op.f('ix_contract_priority'), 'contract', ['priority'], unique=False)
    op.create_table('customer_address',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address_type', sa.Enum('BILLING', 'SHIPPING', name='address_type'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('addr1', sa.String(length=200), nullable=False),
    sa.Column('addr2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_address_customer_id'), 'customer_address', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_address_zip'), 'customer_address', ['zip'], unique=False)
    op.create_table('order',
    sa.Column('web_order_number', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PLACED', 'PUSHED_TO_FACS', 'ACKNOWLEDGED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'QUOTE', name='order_status'), nullable=False),
    sa.Column('payment_type', sa.Enum('CREDIT_CARD', 'PURCHASE_ORDER', name='payment_type'), nullable=False),
    sa.Column('is_quote', sa.Boolean(), nullable=False),
    sa.Column('quote_intent', sa.Enum('BUDGET', 'COMPETITIVE', name='quote_intent'), nullable=True),
    sa.Column('customer_po_number', sa.String(length=100), nullable=True),
    sa.Column('billing_name', sa.String(length=200), nullable=True),
    sa.Column('billing_company', sa.String(length=200), nullable=True),
    sa.Column('billing_addr1', sa.String(length=200), nullable=True),
    sa.Column('billing_addr2', sa.String(length=200), nullable=True),
    sa.Column('billing_city', sa.String(length=100), nullable=True),
    sa.Column('billing_state', sa.String(length=2), nullable=True),
    sa.Column('billing_zip', sa.String(length=20), nullable=True),
    sa.Column('shipping_name', sa.String(length=200), nullable=True),
    sa.Column('shipping_company', sa.String(length=200), nullable=True),
    sa.Column('shipping_addr1', sa.String(length=200), nullable=True),
    sa.Column('shipping_addr2', sa.String(length=200), nullable=True),
    sa.Column('shipping_city', sa.String(length=100), nullable=True),
    sa.Column('shipping_state', sa.String(length=2), nullable=True),
    sa.Column('shipping_zip', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('sales_rep_code', sa.String(length=20), nullable=True),
    sa.Column('referral_source', sa.String(length=100), nullable=True),
    sa.Column('item_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handling_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate_x1000', sa.Integer(), nullable=False),
    sa.Column('tax_code', sa.String(length=20), nullable=True),
    sa.Column('grand_total_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('ship_complete', sa.Boolean(), nullable=False),
    sa.Column('authnet_transaction_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_customer_id'), 'order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_order_customer_po_number'), 'order', ['customer_po_number'], unique=False)
    op.create_index(op.f('ix_order_order_date'), 'order', ['order_date'], unique=False)
    op.create_index(op.f('ix_order_shipping_zip'), 'order', ['shipping_zip'], unique=False)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_web_order_number'), 'order', ['web_order_number'], unique=True)
    op.create_table('product',
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('legacy_wsm_id', sa.Integer(), nullable=True),
    sa.Column('legacy_wsm_stockid', sa.String(length=64), nullable=True),
    sa.Column('legacy_wsm_dealerid', sa.String(length=64), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extended_description', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('series', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('upc', sa.String(length=32), nullable=True),
    sa.Column('meta_title', sa.String(length=500), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('meta_keywords', sa.Text(), nullable=True),
    sa.Column('google_category', sa.String(length=500), nullable=True),
    sa.Column('weight_lb', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('length_in', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('width_in', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('height_in', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('freight_class', sa.String(length=32), nullable=True),
    sa.Column('cta_mode', sa.Enum('ADD_TO_CART', 'QUOTE_SHIPPING', 'BROWSE_ONLY', name='cta_mode'), nullable=False),
    sa.Column('requires_shipping', sa.Boolean(), nullable=False),
    sa.Column('taxable', sa.Boolean(), nullable=False),
    sa.Column('own_box', sa.Boolean(), nullable=False),
    sa.Column('ship_quote', sa.Boolean(), nullable=False),
    sa.Column('free_ground', sa.Integer(), nullable=False),
    sa.Column('handling_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('shipping_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_for_sale', sa.Boolean(), nullable=False),
    sa.Column('login_required', sa.Boolean(), nullable=False),
    sa.Column('group_required', sa.Enum('JOBBER', 'JOBBER_MUNICIPALITY', name='group_requirement'), nullable=True),
    sa.Column('saleprice_hidden', sa.Boolean(), nullable=False),
    sa.Column('legacy_wsm_availability', sa.String(length=32), nullable=True),
    sa.Column('legacy_wsm_url', sa.String(length=1000), nullable=True),
    sa.Column('legacy_wsm_owner', sa.String(length=200), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('email_notes', sa.Text(), nullable=True),
    sa.Column('available_remarks', sa.Text(), nullable=True),
    sa.Column('shipping_remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_brand_active', 'product', ['brand_id', 'is_hidden', 'is_for_sale'], unique=False)
    op.create_index(op.f('ix_product_brand_id'), 'product', ['brand_id'], unique=False)
    op.create_index(op.f('ix_product_cta_mode'), 'product', ['cta_mode'], unique=False)
    op.create_index(op.f('ix_product_freight_class'), 'product', ['freight_class'], unique=False)
    op.create_index(op.f('ix_product_group_required'), 'product', ['group_required'], unique=False)
    op.create_index(op.f('ix_product_is_for_sale'), 'product', ['is_for_sale'], unique=False)
    op.create_index(op.f('ix_product_is_hidden'), 'product', ['is_hidden'], unique=False)
    op.create_index(op.f('ix_product_legacy_wsm_availability'), 'product', ['legacy_wsm_availability'], unique=False)
    op.create_index(op.f('ix_product_legacy_wsm_dealerid'), 'product', ['legacy_wsm_dealerid'], unique=False)
    op.create_index(op.f('ix_product_legacy_wsm_id'), 'product', ['legacy_wsm_id'], unique=True)
    op.create_index(op.f('ix_product_legacy_wsm_stockid'), 'product', ['legacy_wsm_stockid'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_index('ix_product_search', 'product', ['name', 'sku'], unique=False)
    op.create_index(op.f('ix_product_series'), 'product', ['series'], unique=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=True)
    op.create_index(op.f('ix_product_upc'), 'product', ['upc'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'EDITOR', 'CUSTOMER', name='user_role'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('totp_secret', sa.String(length=200), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=200), nullable=True),
    sa.Column('password_reset_token', sa.String(length=200), nullable=True),
    sa.Column('password_reset_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_customer_id'), 'user', ['customer_id'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('audit_log',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('order_fulfillment',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('routing_type', sa.String(length=20), nullable=False),
    sa.Column('facs_warehouse_code', sa.Integer(), nullable=False),
    sa.Column('item_subtotal_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_share_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('handling_share_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_share_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('push_status', sa.Enum('PENDING', 'PUSHED', 'PICKED_UP', 'FAILED', 'REPLAYED', name='facs_push_status'), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('push_attempts', sa.Integer(), nullable=False),
    sa.Column('csv_content', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_index(op.f('ix_order_fulfillment_order_id'), 'order_fulfillment', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_fulfillment_push_status'), 'order_fulfillment', ['push_status'], unique=False)
    op.create_table('order_line',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('backorder_quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('is_freight', sa.Boolean(), nullable=False),
    sa.Column('is_discount', sa.Boolean(), nullable=False),
    sa.Column('is_handling', sa.Boolean(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'line_number', name='uq_order_line_number')
    )
    op.create_index(op.f('ix_order_line_order_id'), 'order_line', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_line_product_id'), 'order_line', ['product_id'], unique=False)
    op.create_index(op.f('ix_order_line_sku'), 'order_line', ['sku'], unique=False)
    op.create_index(op.f('ix_order_line_warehouse_id'), 'order_line', ['warehouse_id'], unique=False)
    op.create_table('product_category',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'category_id', name='uq_product_category')
    )
    op.create_index(op.f('ix_product_category_category_id'), 'product_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_product_category_product_id'), 'product_category', ['product_id'], unique=False)
    op.create_table('product_image',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('legacy_origin', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_product_id'), 'product_image', ['product_id'], unique=False)
    op.create_table('product_inventory',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('on_hand', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'warehouse_id', name='uq_inventory_product_warehouse')
    )
    op.create_index(op.f('ix_product_inventory_product_id'), 'product_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_inventory_warehouse_id'), 'product_inventory', ['warehouse_id'], unique=False)
    op.create_table('product_price',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('map_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('suggested_retail_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('retail_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('jobber_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('dealer_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('municipality_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sale_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sale_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_price')
    op.drop_index(op.f('ix_product_inventory_warehouse_id'), table_name='product_inventory')
    op.drop_index(op.f('ix_product_inventory_product_id'), table_name='product_inventory')
    op.drop_table('product_inventory')
    op.drop_index(op.f('ix_product_image_product_id'), table_name='product_image')
    op.drop_table('product_image')
    op.drop_index(op.f('ix_product_category_product_id'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_category_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_order_line_warehouse_id'), table_name='order_line')
    op.drop_index(op.f('ix_order_line_sku'), table_name='order_line')
    op.drop_index(op.f('ix_order_line_product_id'), table_name='order_line')
    op.drop_index(op.f('ix_order_line_order_id'), table_name='order_line')
    op.drop_table('order_line')
    op.drop_index(op.f('ix_order_fulfillment_push_status'), table_name='order_fulfillment')
    op.drop_index(op.f('ix_order_fulfillment_order_id'), table_name='order_fulfillment')
    op.drop_table('order_fulfillment')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_customer_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_upc'), table_name='product')
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.drop_index(op.f('ix_product_series'), table_name='product')
    op.drop_index('ix_product_search', table_name='product')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_legacy_wsm_stockid'), table_name='product')
    op.drop_index(op.f('ix_product_legacy_wsm_id'), table_name='product')
    op.drop_index(op.f('ix_product_legacy_wsm_dealerid'), table_name='product')
    op.drop_index(op.f('ix_product_legacy_wsm_availability'), table_name='product')
    op.drop_index(op.f('ix_product_is_hidden'), table_name='product')
    op.drop_index(op.f('ix_product_is_for_sale'), table_name='product')
    op.drop_index(op.f('ix_product_group_required'), table_name='product')
    op.drop_index(op.f('ix_product_freight_class'), table_name='product')
    op.drop_index(op.f('ix_product_cta_mode'), table_name='product')
    op.drop_index(op.f('ix_product_brand_id'), table_name='product')
    op.drop_index('ix_product_brand_active', table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_order_web_order_number'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_shipping_zip'), table_name='order')
    op.drop_index(op.f('ix_order_order_date'), table_name='order')
    op.drop_index(op.f('ix_order_customer_po_number'), table_name='order')
    op.drop_index(op.f('ix_order_customer_id'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_customer_address_zip'), table_name='customer_address')
    op.drop_index(op.f('ix_customer_address_customer_id'), table_name='customer_address')
    op.drop_table('customer_address')
    op.drop_index(op.f('ix_contract_priority'), table_name='contract')
    op.drop_index(op.f('ix_contract_part_number'), table_name='contract')
    op.drop_index(op.f('ix_contract_group_code'), table_name='contract')
    op.drop_index(op.f('ix_contract_expiration_date'), table_name='contract')
    op.drop_index(op.f('ix_contract_customer_id'), table_name='contract')
    op.drop_index(op.f('ix_contract_brand'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_warehouse_code'), table_name='warehouse')
    op.drop_table('warehouse')
    op.drop_index(op.f('ix_customer_tier'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_index(op.f('ix_customer_customer_number'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_category_slug'), table_name='category')
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_full_path'), table_name='category')
    op.drop_index(op.f('ix_category_depth'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_brand_slug'), table_name='brand')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_index(op.f('ix_brand_legacy_wsm_prefix'), table_name='brand')
    op.drop_index(op.f('ix_brand_is_featured'), table_name='brand')
    op.drop_table('brand')
    # ### end Alembic commands ###
