-- error_reports — storage for the in-app Issue Recorder (admin + Cloudflare-Access testers).
--
-- WHY THIS FILE EXISTS
-- The Titan site created this table by hand, straight against its database,
-- with no file in the repo. When this site was cloned from Titan it inherited
-- every line of the recorder's code and none of its schema, so the panel
-- recorded, transcribed and uploaded exactly as designed and then lost the
-- report on the final INSERT — a 500 against a relation that was never there.
-- Nothing in the UI said so. Checking the table in beside the code that needs
-- it is the whole point: a fresh database can now never drift from the router
-- again.
--
-- Idempotent — safe to run repeatedly, and safe to run against a database that
-- already has reports in it.
--   PGPASSWORD=... psql -h localhost -p 5433 -U postgres -d nelson_web \
--     -f app/scripts/create_error_reports_table.sql

CREATE TABLE IF NOT EXISTS public.error_reports (
    id                   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                text        NOT NULL DEFAULT '',
    description          text        NOT NULL DEFAULT '',
    route                text        NOT NULL DEFAULT '',
    severity             text        NOT NULL DEFAULT 'normal',
    status               text        NOT NULL DEFAULT 'open',
    reported_by_user_id  integer,
    -- Cloudflare-Access testers have no user row; their email lands here.
    reported_by_username text        NOT NULL DEFAULT '',
    speech_segments      jsonb       NOT NULL DEFAULT '[]'::jsonb,
    click_events         jsonb       NOT NULL DEFAULT '[]'::jsonb,
    pages_visited        jsonb       NOT NULL DEFAULT '[]'::jsonb,
    dom_state            jsonb       NOT NULL DEFAULT '{}'::jsonb,
    mic_diagnostics      jsonb       NOT NULL DEFAULT '{}'::jsonb,
    browser_info         text        NOT NULL DEFAULT '',
    -- Relative path only; the video is served through an admin-gated endpoint,
    -- never from a public static mount — a recording can show any page.
    video_path           text,
    resolution_notes     text,
    created_at           timestamptz NOT NULL DEFAULT now(),
    updated_at           timestamptz NOT NULL DEFAULT now(),
    resolved_at          timestamptz,
    -- Which site filed it. Nelson and Titan keep entirely separate databases,
    -- so this is belt-and-braces: a report pulled out of context still says
    -- where it came from.
    source               text        NOT NULL DEFAULT 'nelson_website'
);

CREATE INDEX IF NOT EXISTS ix_error_reports_created ON public.error_reports (created_at DESC);
CREATE INDEX IF NOT EXISTS ix_error_reports_status  ON public.error_reports (status);

-- Columns added after the table first shipped. Spelled out individually so an
-- older database catches up instead of being left half-formed.
ALTER TABLE public.error_reports
    ADD COLUMN IF NOT EXISTS mic_diagnostics jsonb NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS video_path      text,
    ADD COLUMN IF NOT EXISTS source          text  NOT NULL DEFAULT 'nelson_website';
